# -*- coding: utf-8 -*-
"""Crop Recommendation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhRyPw5DfwhsxuSoQONGhK-HKSR-Yxin
"""

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/crop_recomendation_data/Crop_recommendation.csv'

df = pd.read_csv(file_path)

# Split the dataset into features (X) and target variable (y)
X = df[['Temperature (°C)', 'Humidity (%)']]
y = df['Crop']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_train.values, y_train.values)

y_pred = model.predict(X_test.values)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

temperature = float(input("Enter the temperature (°C): "))
humidity = float(input("Enter the humidity (%): "))
new_weather_conditions = [[temperature, humidity]]

predicted_crop = model.predict(new_weather_conditions)
print(f"Predicted Crop: {predicted_crop}")