# -*- coding: utf-8 -*-
"""Sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uD7qpAYj5sib3sPcoMgcyq2qDbosfPcj
"""

!pip install transformers torch

from transformers import pipeline

# Load a sentiment-analysis pipeline (can be used for emotion detection)
emotion_classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", return_all_scores=True)

texts = [
    "you are bad"
]

results = [emotion_classifier(text) for text in texts]

for text, result in zip(texts, results):
    print(f"Text: {text}")
    print("Emotion Scores:")
    for emotion in result[0]:
        print(f"  {emotion['label']}: {emotion['score']:.2f}")
    print("\n")



""" **For Emotion and tone detection**"""

from transformers import pipeline

# Load the emotion classification model
emotion_classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", return_all_scores=True)

# Load the sentiment analysis model
sentiment_classifier = pipeline("sentiment-analysis")

# Sample texts to analyze
texts = [
    "I can’t believe it! After months of hard work and dedication, I finally got the promotion I’ve been dreaming of. It feels so rewarding to see my efforts pay off, and I’m excited to take on new challenges. My colleagues were so supportive, and we celebrated together with a small party. This is truly one of the happiest moments of my career, and I can’t wait to see what the future holds."
]

# Analyze each text for emotions and sentiment
for text in texts:
    emotion_results = emotion_classifier(text)
    sentiment_result = sentiment_classifier(text)
    print("*******************************************************************************************************************")
    print(f"Text: {text}")

    # Display Emotion Scores
    print("Emotion Scores:")
    for emotion in emotion_results[0]:
        print(f"  {emotion['label']}: {emotion['score']:.2f}")

    # Display Sentiment Result
    print(f"Tone: {sentiment_result[0]['label']} (Confidence: {sentiment_result[0]['score']:.2f})\n")

